-- Expand drug master to ~200 common Indian drugs (Healthplix-style comprehensive coverage)
-- DELETE old 28 rows and re-seed with full catalogue

DELETE FROM drug_master;

INSERT INTO drug_master (brand, generic, strength, form, common_dosages, common_frequencies, common_durations, category) VALUES

-- ═══════════════════════════════════════════════════════════════════════════════
-- ANALGESICS / ANTIPYRETICS
-- ═══════════════════════════════════════════════════════════════════════════════
('Dolo 650',         'Paracetamol',               '650 mg',  'Tablet',     '["650 mg"]',                              '["TDS","BD","SOS"]',        '[3,5]',       'Analgesic / Antipyretic'),
('Crocin 500',       'Paracetamol',               '500 mg',  'Tablet',     '["500 mg"]',                              '["TDS","BD"]',              '[3,5]',       'Analgesic / Antipyretic'),
('Crocin Advance',   'Paracetamol',               '500 mg',  'Tablet',     '["500 mg"]',                              '["TDS","BD"]',              '[3,5]',       'Analgesic / Antipyretic'),
('Calpol',           'Paracetamol Suspension',     '250 mg/5ml', 'Suspension', '["5 ml","10 ml"]',                      '["TDS","BD","SOS"]',        '[3,5]',       'Analgesic / Antipyretic'),
('Paracip',          'Paracetamol',               '500 mg',  'Tablet',     '["500 mg"]',                              '["TDS","BD"]',              '[3,5]',       'Analgesic / Antipyretic'),
('Fepanil',          'Paracetamol',               '650 mg',  'Tablet',     '["650 mg"]',                              '["TDS","BD","SOS"]',        '[3,5]',       'Analgesic / Antipyretic'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- NSAIDs
-- ═══════════════════════════════════════════════════════════════════════════════
('Ibufen',           'Ibuprofen',                 '400 mg',  'Tablet',     '["400 mg","600 mg"]',                     '["BD","TDS"]',              '[3,5,7]',     'NSAID'),
('Brufen',           'Ibuprofen',                 '400 mg',  'Tablet',     '["400 mg"]',                              '["BD","TDS"]',              '[3,5]',       'NSAID'),
('Ibugesic',         'Ibuprofen',                 '200 mg',  'Tablet',     '["200 mg","400 mg"]',                     '["BD"]',                    '[3,5]',       'NSAID'),
('Diclogard',        'Diclofenac Sodium',         '50 mg',   'Tablet',     '["50 mg"]',                               '["BD","TDS"]',              '[3,5]',       'NSAID'),
('Volini',           'Diclofenac Diethylamine',   '1.16%',   'Gel',        '["Apply"]',                               '["BD","TDS"]',              '[7,14]',      'NSAID (Topical)'),
('Voveran',          'Diclofenac Sodium',         '50 mg',   'Tablet',     '["50 mg"]',                               '["BD","TDS"]',              '[3,5]',       'NSAID'),
('Nimulid',          'Nimesulide',                '100 mg',  'Tablet',     '["100 mg"]',                              '["BD","SOS"]',              '[3,5]',       'NSAID'),
('Nexgesic',         'Aceclofenac',               '100 mg',  'Tablet',     '["100 mg"]',                              '["BD"]',                    '[5,7]',       'NSAID'),
('Aceclo Plus',      'Aceclofenac + Paracetamol', '150 mg + 500 mg', 'Tablet', '["150/500 mg"]',                      '["BD","TDS"]',              '[3,5]',       'NSAID / Analgesic'),
('Flexon',           'Diclofenac + Paracetamol',  '50 mg + 500 mg', 'Tablet', '["50/500 mg"]',                          '["BD","TDS"]',              '[3,5]',       'NSAID / Analgesic'),
('Aceproxyvon',      'Aceclofenac + Paracetamol', '100 mg + 325 mg', 'Tablet', '["100/325 mg"]',                       '["BD","TDS"]',              '[3,5]',       'NSAID / Analgesic'),
('Combiflam',        'Ibuprofen + Paracetamol',   '400 mg + 325 mg', 'Tablet', '["400/325 mg"]',                       '["BD","TDS"]',              '[3,5]',       'NSAID / Analgesic'),
('Saridon',          'Paracetamol + Propyphenazone + Caffeine', '500 mg + 200 mg + 50 mg', 'Tablet', '["1 tab"]', '["TDS","SOS"]',    '[3,5]',       'Analgesic'),
('StayHap',          'Tramadol',                  '50 mg',   'Capsule',    '["50 mg"]',                               '["BD","TDS"]',              '[3,5]',       'Opioid Analgesic'),
('Ultracet',         'Tramadol + Paracetamol',    '37.5 mg + 325 mg', 'Tablet', '["37.5/325 mg"]',                     '["TDS"]',                   '[3,5]',       'Opioid Analgesic'),
('Zole Plus',        'Diclofenac + Serratiopeptidase', '50 mg + 10 mg', 'Tablet', '["50/10 mg"]',                     '["BD","TDS"]',              '[3,5]',       'NSAID + Enzyme'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- ANTIBIOTICS
-- ═══════════════════════════════════════════════════════════════════════════════
('Augmentin 625',    'Amoxicillin + Clavulanate', '625 mg',  'Tablet',     '["625 mg"]',                              '["BD","TDS"]',              '[5,7,10]',    'Antibiotic'),
('Augmentin 1.2',    'Amoxicillin + Clavulanate', '1.2 g',   'Injection',  '["1.2 g"]',                               '["BD"]',                    '[5,7]',       'Antibiotic'),
('Amoxyclav 625',    'Amoxicillin + Clavulanate', '625 mg',  'Tablet',     '["625 mg"]',                              '["BD"]',                    '[5,7]',       'Antibiotic'),
('Mox 500',          'Amoxicillin',               '500 mg',  'Capsule',    '["500 mg"]',                              '["TDS"]',                   '[5,7,10]',    'Antibiotic'),
('Amoxicillin GSK',  'Amoxicillin',               '500 mg',  'Capsule',    '["500 mg"]',                              '["TDS"]',                   '[5,7,10]',    'Antibiotic'),
('Azithral 500',     'Azithromycin',              '500 mg',  'Tablet',     '["500 mg"]',                              '["OD"]',                    '[3,5,6]',     'Antibiotic'),
('Azee 500',         'Azithromycin',              '500 mg',  'Tablet',     '["500 mg"]',                              '["OD"]',                    '[3,5]',       'Antibiotic'),
('Azithral 200',     'Azithromycin',              '200 mg/5ml', 'Suspension', '["5 ml","10 ml"]',                     '["OD"]',                    '[3,5]',       'Antibiotic'),
('Zithromax',        'Azithromycin',              '500 mg',  'Tablet',     '["500 mg"]',                              '["OD"]',                    '[3,5]',       'Antibiotic'),
('Cifran',           'Ciprofloxacin',             '500 mg',  'Tablet',     '["500 mg"]',                              '["BD"]',                    '[5,7]',       'Antibiotic'),
('Cifran OD',        'Ciprofloxacin',             '500 mg',  'Tablet (SR)','["500 mg"]',                              '["OD"]',                    '[5,7]',       'Antibiotic'),
('Oflox',            'Ofloxacin',                 '200 mg',  'Tablet',     '["200 mg","400 mg"]',                     '["BD"]',                    '[5,7]',       'Antibiotic'),
('Oflo OW',          'Ofloxacin',                 '200 mg',  'Tablet (OD)', '["200 mg"]',                              '["OD"]',                    '[5,7]',       'Antibiotic'),
('Gatiflo',          'Gatifloxacin',              '400 mg',  'Tablet',     '["400 mg"]',                              '["OD"]',                    '[5,7]',       'Antibiotic'),
('Levoflox 500',     'Levofloxacin',              '500 mg',  'Tablet',     '["500 mg"]',                              '["OD"]',                    '[5,7,10]',    'Antibiotic'),
('Norflox 400',      'Norfloxacin',               '400 mg',  'Tablet',     '["400 mg"]',                              '["BD"]',                    '[5,7]',       'Antibiotic'),
('Norflox TZ',       'Norfloxacin + Tinidazole',  '400 mg + 600 mg', 'Tablet', '["400/600 mg"]',                     '["BD"]',                    '[5,7]',       'Antibiotic'),
('Metronidazole 400','Metronidazole',             '400 mg',  'Tablet',     '["400 mg"]',                              '["TDS"]',                   '[5,7]',       'Antibiotic'),
('Flagyl 400',       'Metronidazole',             '400 mg',  'Tablet',     '["400 mg"]',                              '["TDS","BD"]',              '[5,7]',       'Antibiotic'),
('Tiniba 500',       'Tinidazole',                '500 mg',  'Tablet',     '["500 mg"]',                              '["BD"]',                    '[3,5]',       'Antibiotic'),
('Pan 40',           'Pantoprazole',              '40 mg',   'Tablet',     '["40 mg"]',                               '["OD"]',                    '[14,28]',     'Antibiotic (H. pylori)'),
('Cefixime 200',     'Cefixime',                  '200 mg',  'Tablet',     '["200 mg"]',                              '["BD","OD"]',               '[5,7,10]',    'Cephalosporin'),
('Taxim 200',        'Cefixime',                  '200 mg',  'Tablet',     '["200 mg"]',                              '["BD"]',                    '[5,7]',       'Cephalosporin'),
('Cefpodoxime Proxetil','Cefpodoxime',            '200 mg',  'Tablet',     '["200 mg"]',                              '["BD"]',                    '[5,7,10]',    'Cephalosporin'),
('Cefxime 100',      'Cefixime',                  '100 mg/5ml', 'Suspension', '["5 ml"]',                             '["BD"]',                    '[5,7]',       'Cephalosporin'),
('Clavam 625',       'Amoxicillin + Clavulanate', '625 mg',  'Tablet',     '["625 mg"]',                              '["BD"]',                    '[5,7]',       'Antibiotic'),
('Pencivir',         'Penciclovir',               '1%',      'Cream',      '["Apply"]',                               '["5x daily"]',              '[5]',         'Antiviral'),
('Acyclovir 400',    'Acyclovir',                 '400 mg',  'Tablet',     '["400 mg"]',                              '["TDS","5x daily"]',        '[5,7]',       'Antiviral'),
('Oseltamivir 75',   'Oseltamivir',               '75 mg',   'Capsule',    '["75 mg"]',                               '["BD"]',                    '[5]',         'Antiviral'),
('Fluconazole 150',  'Fluconazole',               '150 mg',  'Tablet',     '["150 mg"]',                              '["Weekly x2-3"]',          '[2,3]', 'Antifungal'),
('ITRACA 100',       'Itraconazole',              '100 mg',  'Capsule',    '["100 mg"]',                              '["BD"]',                    '[7,14]',      'Antifungal'),
('Candid Cream',     'Clotrimazole',              '1%',      'Cream',      '["Apply"]',                               '["BD"]',                    '[14,28]',     'Antifungal'),
('Candiforce 150',   'Fluconazole',               '150 mg',  'Capsule',    '["150 mg"]',                              '["Weekly"]',                '[2,3]', 'Antifungal'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- GASTRO-INTESTINAL / GI
-- ═══════════════════════════════════════════════════════════════════════════════
('Pantop 40',        'Pantoprazole',              '40 mg',   'Tablet',     '["40 mg"]',                               '["OD"]',                    '[14,28]',     'PPI'),
('Pan 40 DS',        'Pantoprazole',              '40 mg',   'Tablet (DR)', '["40 mg"]',                              '["OD"]',                    '[14,28]',     'PPI'),
('Pantodac 40',      'Pantoprazole',              '40 mg',   'Tablet',     '["40 mg"]',                               '["OD"]',                    '[14,28]',     'PPI'),
('Razo 20',          'Rabeprazole',               '20 mg',   'Tablet',     '["20 mg"]',                               '["OD"]',                    '[14,28]',     'PPI'),
('Rabicip 20',       'Rabeprazole',               '20 mg',   'Tablet',     '["20 mg"]',                               '["OD"]',                    '[14,28]',     'PPI'),
('Pan-D',            'Pantoprazole + Domperidone','40 mg',   'Capsule',    '["40 mg"]',                               '["OD"]',                    '[14,28]',     'PPI + Prokinetic'),
('Dompan-D',         'Pantoprazole + Domperidone','40 mg',   'Capsule',    '["40 mg"]',                               '["OD"]',                    '[14,28]',     'PPI + Prokinetic'),
('Pan 20',           'Pantoprazole',              '20 mg',   'Tablet',     '["20 mg"]',                               '["OD"]',                    '[14,28]',     'PPI'),
('Rablet 20',        'Rabeprazole',               '20 mg',   'Tablet',     '["20 mg"]',                               '["OD"]',                    '[14,28]',     'PPI'),
('Omez 20',          'Omeprazole',                '20 mg',   'Capsule',    '["20 mg"]',                               '["OD"]',                    '[14,28]',     'PPI'),
('Omez DSR',         'Omeprazole + Domperidone',  '20 mg',   'Capsule',    '["20 mg"]',                               '["OD"]',                    '[14,28]',     'PPI + Prokinetic'),
('Esomep 40',        'Esomeprazole',              '40 mg',   'Tablet',     '["40 mg"]',                               '["OD"]',                    '[14,28]',     'PPI'),
('Razodoc-D',        'Rabeprazole + Domperidone', '20 mg',   'Tablet',     '["20 mg"]',                               '["OD"]',                    '[14,28]',     'PPI + Prokinetic'),
('Gelusil MPS',      'Aluminium + Magnesium + Simethicone', 'Suspension', 'Syrup', '["10 ml"]',          '["TDS","QID"]',              '[7,14]',      'Antacid'),
('Digene Gel',       'Aluminium + Magnesium + Simethicone', 'Suspension', 'Gel',   '["10 ml"]',              '["TDS","SOS"]',              '[7,14]',      'Antacid'),
('Mucaine Gel',      'Oxetacaine + Aluminium + Magnesium', 'Syrup', 'Syrup',     '["10 ml"]',                              '["TDS"]',                   '[7,14]',      'Antacid + Analgesic'),
('Sucrafil O',       'Sucralfate',                '1 g',     'Tablet (OD)','["1 g"]',                                 '["BD","TDS"]',              '[14,28]',     'Mucosal Protectant'),
('Ulcimin',          'Sucralfate',                '1 g',     'Suspension', '["10 ml"]',                               '["TDS"]',                   '[14,28]',     'Mucosal Protectant'),
('Ryke',             'Ranitidine',                '150 mg',  'Tablet',     '["150 mg","300 mg"]',                     '["BD"]',                    '[14,28]',     'H2 Blocker'),
('Gasex',            'Trebekin Blend',            '1 tab',   'Tablet',     '["1 tab"]',                               '["TDS"]',                   '[14,30]',     'Carminative'),
('Cremaffin Plus',   'Liquid Paraffin + Sodium',  '15 ml',   'Syrup',      '["15 ml"]',                               '["HS"]',                    '[7,14]',      'Laxative'),
('Lactulose 345',    'Lactulose',                 '345 mg/ml','Syrup',     '["15 ml","30 ml"]',                       '["BD"]',                    '[7,14]',      'Osmotic Laxative'),
('Looz',             'Lactulose',                 '10 g',    'Sachet',     '["1 sachet"]',                            '["BD"]',                    '[7,14]',      'Osmotic Laxative'),
('Smecta',           'Diosmectite',               '3 g',     'Sachet',     '["3 g"]',                                 '["TDS"]',                   '[3,5]',       'Antidiarrheal'),
('Eldoper',          'Loperamide',                '2 mg',    'Capsule',    '["2 mg"]',                                '["BD","SOS"]',              '[3,5]',       'Antidiarrheal'),
('ORS',              'Oral Rehydration Salts',    '1 sachet','Powder',     '["1 sachet in 1L"]',                      '["Ad lib"]',                '[3,5]',       'ORS'),
('Emset',            'Ondansetron',               '4 mg',    'Tablet',     '["4 mg"]',                                '["BD","SOS"]',              '[3,5]',       'Antiemetic'),
('Ondem 4',          'Ondansetron',               '4 mg',    'Tablet',     '["4 mg"]',                                '["BD","SOS"]',              '[3,5]',       'Antiemetic'),
('Domperidone 10',   'Domperidone',               '10 mg',   'Tablet',     '["10 mg"]',                               '["TDS","BD"]',              '[7,14]',      'Prokinetic'),
('Motilium',         'Domperidone',               '10 mg',   'Tablet',     '["10 mg"]',                               '["TDS","BD"]',              '[7,14]',      'Prokinetic'),
('Nexpro 40',        'Esomeprazole',              '40 mg',   'Tablet',     '["40 mg"]',                               '["OD"]',                    '[14,28]',     'PPI'),
('Levsoza',          'Levosulpiride',             '75 mg',   'Tablet',     '["75 mg"]',                               '["BD"]',                    '[14,28]',     'Prokinetic'),
('Itopan',           'Itopride',                  '50 mg',   'Tablet',     '["50 mg"]',                               '["TDS"]',                   '[14,28]',     'Prokinetic'),
('Zibac',            'Itopride',                  '150 mg',  'Tablet (SR)','["150 mg"]',                              '["OD"]',                    '[14,28]',     'Prokinetic'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- CARDIOVASCULAR
-- ═══════════════════════════════════════════════════════════════════════════════
('Amlodac 5',        'Amlodipine',                '5 mg',    'Tablet',     '["5 mg"]',                                '["OD"]',                    '[30,60]',     'CCB'),
('Amlodac 10',       'Amlodipine',                '10 mg',   'Tablet',     '["10 mg"]',                               '["OD"]',                    '[30,60]',     'CCB'),
('Stamlo 5',         'Amlodipine',                '5 mg',    'Tablet',     '["5 mg"]',                                '["OD"]',                    '[30,60]',     'CCB'),
('Telma 40',         'Telmisartan',               '40 mg',   'Tablet',     '["40 mg","80 mg"]',                       '["OD"]',                    '[30,60]',     'ARB'),
('Telma H',          'Telmisartan + HCTZ',        '40/12.5 mg','Tablet',  '["40/12.5 mg"]',                          '["OD"]',                    '[30,60]',     'ARB + Diuretic'),
('Telma AM',         'Telmisartan + Amlodipine',  '40/5 mg', 'Tablet',     '["40/5 mg"]',                             '["OD"]',                    '[30,60]',     'ARB + CCB'),
('Telpres 40',       'Telmisartan',               '40 mg',   'Tablet',     '["40 mg"]',                               '["OD"]',                    '[30,60]',     'ARB'),
('Losartan 50',      'Losartan',                  '50 mg',   'Tablet',     '["50 mg"]',                               '["OD"]',                    '[30,60]',     'ARB'),
('Cozaar 50',        'Losartan',                  '50 mg',   'Tablet',     '["50 mg"]',                               '["OD"]',                    '[30,60]',     'ARB'),
('Olmezest 40',      'Olmesartan',                '40 mg',   'Tablet',     '["20 mg","40 mg"]',                       '["OD"]',                    '[30,60]',     'ARB'),
('Olmetrust 40',     'Olmesartan + Amlodipine',   '40/5 mg', 'Tablet',     '["40/5 mg"]',                             '["OD"]',                    '[30,60]',     'ARB + CCB'),
('Enam 5',           'Enalapril',                 '5 mg',    'Tablet',     '["5 mg","10 mg"]',                        '["OD","BD"]',               '[30,60]',     'ACE Inhibitor'),
('Lisinopril 10',    'Lisinopril',                '10 mg',   'Tablet',     '["10 mg"]',                               '["OD"]',                    '[30,60]',     'ACE Inhibitor'),
('Met XL 50',        'Metoprolol Succinate',      '50 mg',   'Tablet (SR)','["50 mg","100 mg"]',                      '["OD"]',                    '[30,60]',     'Beta-blocker'),
('Metolar 50',       'Metoprolol Tartrate',       '50 mg',   'Tablet',     '["50 mg"]',                               '["BD"]',                    '[30,60]',     'Beta-blocker'),
('Metolar 25',       'Metoprolol Tartrate',       '25 mg',   'Tablet',     '["25 mg"]',                               '["BD"]',                    '[30,60]',     'Beta-blocker'),
('Bisoprolol 5',     'Bisoprolol',                '5 mg',    'Tablet',     '["5 mg"]',                                '["OD"]',                    '[30,60]',     'Beta-blocker'),
('Aten 50',          'Atenolol',                  '50 mg',   'Tablet',     '["50 mg"]',                               '["OD"]',                    '[30,60]',     'Beta-blocker'),
('Aten 25',          'Atenolol',                  '25 mg',   'Tablet',     '["25 mg"]',                               '["OD"]',                    '[30,60]',     'Beta-blocker'),
('Ecosprin 75',      'Aspirin',                   '75 mg',   'Tablet',     '["75 mg"]',                               '["OD"]',                    '[30,60]',     'Antiplatelet'),
('Ecosprin AV 75',   'Aspirin + Atorvastatin',    '75/10 mg','Tablet',     '["75/10 mg"]',                            '["OD","HS"]',               '[30,60]',     'Antiplatelet + Statin'),
('Plavix 75',        'Clopidogrel',               '75 mg',   'Tablet',     '["75 mg"]',                               '["OD"]',                    '[30,60,90]',  'Antiplatelet'),
('Atorva 10',        'Atorvastatin',              '10 mg',   'Tablet',     '["10 mg"]',                               '["HS"]',                    '[30,60,90]',  'Statin'),
('Atorva 20',        'Atorvastatin',              '20 mg',   'Tablet',     '["20 mg"]',                               '["HS"]',                    '[30,60,90]',  'Statin'),
('Torvas 10',        'Atorvastatin',              '10 mg',   'Tablet',     '["10 mg"]',                               '["HS"]',                    '[30,60]',     'Statin'),
('Stator 20',        'Atorvastatin',              '20 mg',   'Tablet',     '["20 mg"]',                               '["HS"]',                    '[30,60,90]',  'Statin'),
('Rozavel 10',       'Rosuvastatin',              '10 mg',   'Tablet',     '["5 mg","10 mg"]',                        '["HS"]',                    '[30,60,90]',  'Statin'),
('Rosuvas 10',       'Rosuvastatin',              '10 mg',   'Tablet',     '["5 mg","10 mg"]',                        '["HS"]',                    '[30,60,90]',  'Statin'),
('Rozavel F',         'Rosuvastatin + Fenofibrate','10/160 mg','Tablet',   '["10/160 mg"]',                           '["HS"]',                    '[30,60,90]',  'Statin + Fibrate'),
('Torballyx 40',     'Ticagrelor',               '90 mg',   'Tablet',     '["90 mg"]',                               '["BD"]',                    '[30,60,90]',  'Antiplatelet'),
('Isordil 5',        'Isosorbide Dinitrate',      '5 mg',    'Tablet (SL)','["5 mg"]',                                '["SOS"]',                   '[0]',         'Nitrate'),
('Sorbitrate 5',     'Isosorbide Dinitrate',      '5 mg',    'Sublingual', '["5 mg"]',                                '["SOS"]',                   '[0]',         'Nitrate'),
('Nicardia 10',      'Nifedipine',                '10 mg',   'Capsule',    '["10 mg"]',                               '["TDS"]',                   '[30,60]',     'CCB'),
('Cardace 2.5',      'Ramipril',                  '2.5 mg',  'Capsule',    '["2.5 mg","5 mg"]',                       '["OD"]',                    '[30,60]',     'ACE Inhibitor'),
('Cardace 5',        'Ramipril',                  '5 mg',    'Capsule',    '["5 mg"]',                                '["OD"]',                    '[30,60]',     'ACE Inhibitor'),
('Ramistar 2.5',     'Ramipril',                  '2.5 mg',  'Tablet',     '["2.5 mg"]',                              '["OD"]',                    '[30,60]',     'ACE Inhibitor'),
('Aztor ASP 75',     'Aspirin + Atorvastatin',    '75/10 mg','Tablet',     '["75/10 mg"]',                            '["OD"]',                    '[30,60]',     'Antiplatelet + Statin'),
('Dilzem CD 120',    'Diltiazem',                 '120 mg',  'Capsule (SR)','["120 mg"]',                             '["OD"]',                    '[30,60]',     'CCB'),
('Digoxin 0.25',     'Digoxin',                   '0.25 mg', 'Tablet',     '["0.25 mg"]',                             '["OD"]',                    '[30,60,90]',  'Cardiac Glycoside'),
('Amiodarone 200',   'Amiodarone',                '200 mg',  'Tablet',     '["200 mg"]',                              '["OD"]',                    '[30,60,90]',  'Antiarrhythmic'),
('Spironolactone 25','Spironolactone',            '25 mg',   'Tablet',     '["25 mg","50 mg"]',                       '["OD"]',                    '[30,60]',     'Potassium-sparing Diuretic'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- DIABETES
-- ═══════════════════════════════════════════════════════════════════════════════
('Glycomet 500',     'Metformin',                 '500 mg',  'Tablet',     '["500 mg"]',                              '["BD"]',                    '[30,60,90]',  'Antidiabetic'),
('Glycomet GP 0.5',  'Glimepiride + Metformin',   '0.5 mg + 500 mg', 'Tablet', '["0.5/500 mg"]',                    '["BD"]',                    '[30,60,90]',  'Antidiabetic'),
('Glycomet GP 1',    'Glimepiride + Metformin',   '1 mg + 500 mg', 'Tablet',   '["1/500 mg"]',                         '["BD"]',                    '[30,60,90]',  'Antidiabetic'),
('Glycomet GP 2',    'Glimepiride + Metformin',   '2 mg + 500 mg', 'Tablet',   '["2/500 mg"]',                         '["BD"]',                    '[30,60,90]',  'Antidiabetic'),
('Glycomet SR 500',  'Metformin',                 '500 mg',  'Tablet (SR)','["500 mg","1000 mg"]',                   '["BD"]',                    '[30,60,90]',  'Antidiabetic'),
('Metformin 500',    'Metformin',                 '500 mg',  'Tablet',     '["500 mg"]',                              '["BD"]',                    '[30,60,90]',  'Antidiabetic'),
('Metformin 850',    'Metformin',                 '850 mg',  'Tablet',     '["850 mg"]',                              '["BD"]',                    '[30,60,90]',  'Antidiabetic'),
('Glucobay 50',      'Acarbose',                  '50 mg',   'Tablet',     '["50 mg"]',                               '["TDS"]',                   '[30,60]',     'Alpha-glucosidase Inhibitor'),
('Glizid M',         'Glimepiride + Metformin',   '1 mg + 500 mg', 'Tablet', '["1/500 mg"]',                           '["BD"]',                    '[30,60,90]',  'Antidiabetic'),
('Amaryl M 1',       'Glimepiride + Metformin',   '1 mg + 500 mg', 'Tablet', '["1/500 mg"]',                           '["BD"]',                    '[30,60,90]',  'Antidiabetic'),
('Amaryl M 2',       'Glimepiride + Metformin',   '2 mg + 500 mg', 'Tablet', '["2/500 mg"]',                           '["BD"]',                    '[30,60,90]',  'Antidiabetic'),
('Amaryl 2',         'Glimepiride',               '2 mg',    'Tablet',     '["1 mg","2 mg"]',                         '["OD"]',                    '[30,60,90]',  'Sulfonylurea'),
('Glyuric 100',      'Gliclazide',                '100 mg',  'Tablet (MR)','["100 mg"]',                              '["OD"]',                    '[30,60,90]',  'Sulfonylurea'),
('Glyciphage SR 500','Metformin SR',              '500 mg',  'Tablet (SR)','["500 mg","1000 mg"]',                   '["BD"]',                    '[30,60,90]',  'Antidiabetic'),
('Januvia 100',      'Sitagliptin',               '100 mg',  'Tablet',     '["100 mg"]',                              '["OD"]',                    '[30,60,90]',  'DPP-4 Inhibitor'),
('Jalra 50',         'Vildagliptin',              '50 mg',   'Tablet',     '["50 mg"]',                               '["BD"]',                    '[30,60,90]',  'DPP-4 Inhibitor'),
('Zomelis 50',       'Vildagliptin + Metformin',  '50/500 mg','Tablet',    '["50/500 mg"]',                           '["BD"]',                    '[30,60,90]',  'DPP-4 + Metformin'),
('Sustainerm XR 1',  'Empagliflozin + Metformin', '10/500 mg','Tablet (XR)','["10/500 mg"]',                         '["OD"]',                    '[30,60,90]',  'SGLT2 + Metformin'),
('Jardiance 10',     'Empagliflozin',             '10 mg',   'Tablet',     '["10 mg","25 mg"]',                       '["OD"]',                    '[30,60,90]',  'SGLT2 Inhibitor'),
('Forxiga 10',       'Dapagliflozin',             '10 mg',   'Tablet',     '["10 mg"]',                               '["OD"]',                    '[30,60,90]',  'SGLT2 Inhibitor'),
('Glyxambi 10',      'Empagliflozin + Linagliptin','10/5 mg', 'Tablet',     '["10/5 mg"]',                            '["OD"]',                    '[30,60,90]',  'SGLT2 + DPP-4'),
('Actrapid 40',      'Insulin Human (Soluble)',   '40 IU/ml','Injection',  '["40 IU"]',                               '["As directed"]',           '[0]',         'Insulin'),
('Lantus 100',       'Insulin Glargine',          '100 IU/ml','Pen Fill',  '["100 IU"]',                              '["OD"]',                    '[0]',         'Basal Insulin'),
('Mixtard 30/70',    'Insulin Human 30/70',       '100 IU/ml','Injection', '["100 IU"]',                              '["BD"]',                    '[0]',         'Pre-mixed Insulin'),
('NovoRapid 100',    'Insulin Aspart',            '100 IU/ml','Pen Fill',  '["100 IU"]',                              '["As directed"]',           '[0]',         'Rapid-acting Insulin'),
('Wosulin 30/70',    'Insulin Human 30/70',       '100 IU/ml','Injection', '["100 IU"]',                              '["BD"]',                    '[0]',         'Pre-mixed Insulin'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- RESPIRATORY
-- ═══════════════════════════════════════════════════════════════════════════════
('Montair LC',        'Montelukast + Levocetirizine','10/5 mg','Tablet',  '["10/5 mg"]',                             '["HS"]',                    '[14,30]',     'Anti-asthmatic'),
('Montair 10',        'Montelukast',              '10 mg',   'Tablet',     '["10 mg"]',                               '["HS"]',                    '[14,30]',     'Anti-asthmatic'),
('Montair FX',        'Montelukast + Fexofenadine','120 mg + 10 mg', 'Tablet', '["120/10 mg"]',                       '["OD"]',                    '[14,30]',     'Anti-allergic + Anti-asthmatic'),
('Kofarest',          'Montelukast + Ambroxol',   '10/75 mg', 'Tablet (SR)','["10/75 mg"]',                          '["OD"]',                    '[14,30]',     'Anti-asthmatic + Mucolytic'),
('Salbutamol 100',   'Salbutamol',                '100 mcg', 'Inhaler',    '["2 puffs"]',                             '["BD","SOS"]',              '[14,30]',     'Bronchodilator'),
('Asthalin 100',     'Salbutamol',                '100 mcg', 'Inhaler',    '["2 puffs"]',                             '["BD","SOS"]',              '[14,30]',     'Bronchodilator'),
('Asthalin Respules','Salbutamol',                '2.5 mg',  'Nebulization','["2.5 mg"]',                            '["BD"]',                    '[14,30]',     'Bronchodilator'),
('Budecort 200',     'Budesonide',                '200 mcg', 'Inhaler',    '["2 puffs"]',                             '["BD"]',                    '[30,60]',     'Inhaled Corticosteroid'),
('Budecort Respules','Budesonide',                '0.5 mg',  'Nebulization','["0.5 mg"]',                            '["BD"]',                    '[14,30]',     'Inhaled Corticosteroid'),
('Foracort 200',     'Budesonide + Formoterol',   '200/6 mcg','Inhaler',   '["200/6 mcg"]',                          '["BD"]',                    '[30,60]',     'ICS + LABA'),
('Foracort 400',     'Budesonide + Formoterol',   '400/6 mcg','Inhaler',   '["400/6 mcg"]',                          '["BD"]',                    '[30,60]',     'ICS + LABA'),
('Duolin 2.5',       'Ipratropium + Salbutamol',  '2.5/0.5 mg/2.5ml', 'Nebulization', '["2.5 ml"]',       '["TDS"]',                   '[14,30]',     'Bronchodilator'),
('Ambrolite D',       'Ambroxol + Salbutamol + Guaifenesin','Syrup','Syrup','["5 ml"]',                              '["TDS"]',                   '[7,14]',      'Mucolytic'),
('Mucolite 300',      'Ambroxol',                  '300 mg',  'Tablet (SR)','["300 mg"]',                              '["OD"]',                    '[7,14]',      'Mucolytic'),
('Mucolite Syrup',    'Ambroxol',                  '75 mg/5ml','Syrup',    '["5 ml","10 ml"]',                        '["TDS"]',                   '[7,14]',      'Mucolytic'),
('Ascoril LS',        'Levosalbutamol',            '1 mg/5ml','Syrup',      '["5 ml"]',                                '["TDS"]',                   '[7,14]',      'Bronchodilator'),
('Sinarest',          'Paracetamol + Phenylephrine + Chlorpheniramine', 'Tablet', 'Tablet', '["1 tab"]', '["TDS"]',  '[3,5]',       'Cold / Sinusitis'),
('Cetirizine 10',     'Cetirizine',                '10 mg',   'Tablet',     '["10 mg"]',                               '["OD"]',                    '[7,14]',      'Antiallergic'),
('Cetzine 10',        'Cetirizine',                '10 mg',   'Tablet',     '["10 mg"]',                               '["OD"]',                    '[7,14]',      'Antiallergic'),
('Levocet 5',         'Levocetirizine',            '5 mg',    'Tablet',     '["5 mg"]',                                '["OD"]',                    '[7,14]',      'Antiallergic'),
('Xyzal 5',           'Levocetirizine',            '5 mg',    'Tablet',     '["5 mg"]',                                '["OD"]',                    '[7,14]',      'Antiallergic'),
('Alerid 10',         'Cetirizine',                '10 mg',   'Tablet',     '["10 mg"]',                               '["OD"]',                    '[7,14]',      'Antiallergic'),
('Allegra 120',       'Fexofenadine',              '120 mg',  'Tablet',     '["120 mg"]',                              '["OD"]',                    '[7,14]',      'Antiallergic'),
('Allegra 180',       'Fexofenadine',              '180 mg',  'Tablet',     '["180 mg"]',                              '["OD"]',                    '[7,14]',      'Antiallergic'),
('Fexigran',          'Fexofenadine',              '120 mg',  'Tablet',     '["120 mg"]',                              '["OD"]',                    '[7,14]',      'Antiallergic'),
('Phenergan 25',      'Promethazine',              '25 mg',   'Tablet',     '["25 mg"]',                               '["HS"]',                    '[3,5]',       'Antihistamine'),
('Phenergan Syrup',   'Promethazine',              '5 mg/5ml','Syrup',      '["5 ml","10 ml"]',                        '["HS"]',                    '[3,5]',       'Antihistamine'),
('Zincovit',          'Multivitamin + Zinc',       '1 tab',   'Tablet',     '["1 tab"]',                               '["OD"]',                    '[30,60]',     'Supplement'),
('Becosules',         'Multivitamin',              '1 cap',   'Capsule',    '["1 cap"]',                               '["OD"]',                    '[30,60]',     'Supplement'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- VITAMINS / SUPPLEMENTS
-- ═══════════════════════════════════════════════════════════════════════════════
('D-Rise 60K',       'Vitamin D3',                '60000 IU','Capsule',    '["60000 IU"]',                           '["Weekly x4-8"]',          '[4,8]', 'Vitamin D'),
('D3-Must 60K',      'Vitamin D3',                '60000 IU','Capsule',    '["60000 IU"]',                           '["Weekly x4-8"]',          '[4,8]', 'Vitamin D'),
('Telma D3',         'Vitamin D3',                '60000 IU','Sachet',     '["60000 IU"]',                           '["Weekly x4-8"]',          '[4,8]', 'Vitamin D'),
('Neurobion Forte',   'Methylcobalamin + B1 + B6 + B12', 'Injection', 'Injection', '["1 ml"]',                    '["OD","Alternate day"]',    '[14,30]',     'Neurotropic Vitamin'),
('Neurobion Forte Tab','Methylcobalamin + B1 + B6 + B12','Tablet','Tablet', '["1 tab"]',                              '["OD"]',                    '[30,60]',     'Neurotropic Vitamin'),
('Methylcobal 1500',  'Methylcobalamin',          '1500 mcg','Tablet',     '["1500 mcg"]',                            '["OD"]',                    '[30,60,90]',  'Vitamin B12'),
('Neurcobal 1500',    'Methylcobalamin',          '1500 mcg','Tablet',     '["1500 mcg"]',                            '["OD"]',                    '[30,60,90]',  'Vitamin B12'),
('Iron + Folic',      'Ferrous Fumarate + Folic Acid','210 mg + 0.15 mg', 'Tablet', '["1 tab"]',                '["OD"]',                    '[30,60,90]',  'Iron Supplement'),
('Feronia XT',        'Ferric Pyrophosphate Citrate','100 mg', 'Tablet',    '["100 mg"]',                              '["OD"]',                    '[30,60,90]',  'Iron Supplement'),
('Hemfer XT',         'Elemental Iron + Folic Acid','100 mg', 'Tablet',     '["100 mg"]',                              '["OD"]',                    '[30,60,90]',  'Iron Supplement'),
('Thyronorm 50',     'Levothyroxine',            '50 mcg',  'Tablet',     '["50 mcg"]',                              '["OD"]',                    '[60,90]',     'Thyroid'),
('Thyronorm 25',     'Levothyroxine',            '25 mcg',  'Tablet',     '["25 mcg"]',                              '["OD"]',                    '[60,90]',     'Thyroid'),
('Thyronorm 100',    'Levothyroxine',            '100 mcg', 'Tablet',     '["100 mcg"]',                             '["OD"]',                    '[60,90]',     'Thyroid'),
('Thyrocab',         'Levothyroxine + Selenium',  '50 mcg',  'Tablet',     '["50 mcg"]',                              '["OD"]',                    '[60,90]',     'Thyroid + Selenium'),
('Calciquick D3',    'Vitamin D3 + Calcium',      '60000 IU','Tablet',     '["60000 IU"]',                           '["Weekly x4"]',            '[4]',   'Calcium + Vitamin D'),
('Calcirol',         'Vitamin D3',                '60000 IU','Capsule',    '["60000 IU"]',                           '["Weekly x4-8"]',          '[4,8]', 'Vitamin D'),
('Shelcal 500',      'Calcium + Vitamin D3',      '500 mg',  'Tablet',     '["500 mg"]',                              '["OD","BD"]',               '[30,60]',     'Calcium'),
('Ostocal D3',       'Calcium Carbonate + D3',    '500 mg + 250 IU', 'Tablet', '["500 mg"]',                         '["OD"]',                    '[30,60]',     'Calcium'),
('Osteofos 350',     'Calcium Carbonate',         '350 mg',  'Tablet',     '["350 mg"]',                              '["OD"]',                    '[30,60]',     'Calcium'),
('Omega 3 Fish Oil', 'Omega-3 Fatty Acids',       '1000 mg', 'Capsule',    '["1000 mg"]',                             '["OD"]',                    '[30,60,90]',  'Nutraceutical'),
('Becadexamin',      'Multivitamin + Mineral',    '1 cap',   'Capsule',    '["1 cap"]',                               '["OD"]',                    '[30,60]',     'Multivitamin'),
('Centrum Silver',    'Multivitamin + Mineral',   '1 tab',   'Tablet',     '["1 tab"]',                               '["OD"]',                    '[30,60]',     'Multivitamin'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- PSYCHIATRIC / NEURO
-- ═══════════════════════════════════════════════════════════════════════════════
('Azep 0.25',        'Alprazolam',                '0.25 mg', 'Tablet',     '["0.25 mg"]',                             '["HS"]',                    '[14,30]',     'Anxiolytic'),
('Alprax 0.25',      'Alprazolam',                '0.25 mg', 'Tablet',     '["0.25 mg"]',                             '["HS"]',                    '[14,30]',     'Anxiolytic'),
('Alprax 0.5',       'Alprazolam',                '0.5 mg',  'Tablet',     '["0.5 mg"]',                              '["BD"]',                    '[14,30]',     'Anxiolytic'),
('Anxit 0.25',       'Alprazolam',                '0.25 mg', 'Tablet',     '["0.25 mg"]',                             '["HS"]',                    '[14,30]',     'Anxiolytic'),
('Trazodone 50',     'Trazodone',                 '50 mg',   'Tablet',     '["50 mg"]',                               '["HS"]',                    '[30,60]',     'Antidepressant'),
('Doxepin 10',       'Doxepin',                   '10 mg',   'Capsule',    '["10 mg"]',                               '["HS"]',                    '[30,60]',     'Antidepressant'),
('Flunil 20',        'Fluoxetine',                '20 mg',   'Capsule',    '["20 mg"]',                               '["OD"]',                    '[30,60,90]',  'SSRI'),
('Depakote 250',     'Divalproex Sodium',         '250 mg',  'Tablet (EC)','["250 mg"]',                              '["BD"]',                    '[30,60,90]',  'Mood Stabilizer'),
('Valparin 500',     'Sodium Valproate',          '500 mg',  'Tablet',     '["500 mg"]',                              '["BD"]',                    '[30,60,90]',  'Mood Stabilizer'),
('Epival 500',       'Sodium Valproate',          '500 mg',  'Tablet',     '["500 mg"]',                              '["BD"]',                    '[30,60,90]',  'Mood Stabilizer'),
('Lamictal 25',      'Lamotrigine',               '25 mg',   'Tablet',     '["25 mg","50 mg"]',                       '["BD"]',                    '[30,60,90]',  'Mood Stabilizer'),
('Leptic 25',        'Olanzapine',                '2.5 mg',  'Tablet',     '["2.5 mg","5 mg"]',                       '["HS"]',                    '[30,60,90]',  'Antipsychotic'),
('Oleanz 10',        'Olanzapine',                '10 mg',   'Tablet',     '["10 mg"]',                               '["HS"]',                    '[30,60,90]',  'Antipsychotic'),
('Resperidone 2',    'Risperidone',               '2 mg',    'Tablet',     '["1 mg","2 mg"]',                         '["BD"]',                    '[30,60,90]',  'Antipsychotic'),
('Lithosun SR 400',  'Lithium Carbonate',         '400 mg',  'Tablet (SR)','["400 mg"]',                              '["BD"]',                    '[30,60,90]',  'Mood Stabilizer'),
('Gabapin 300',      'Gabapentin',                '300 mg',  'Capsule',    '["300 mg"]',                              '["TDS"]',                   '[30,60,90]',  'Anticonvulsant'),
('Pregabalin 75',    'Pregabalin',                '75 mg',   'Capsule',    '["75 mg"]',                               '["BD"]',                    '[30,60,90]',  'Anticonvulsant'),
('Pregabid 75',      'Pregabalin + Methylcobalamin','75 mg + 750 mcg', 'Capsule', '["75/750 mcg"]',                '["BD"]',                    '[30,60,90]',  'Anticonvulsant'),
('Levetiracetam 500','Levetiracetam',             '500 mg',  'Tablet',     '["500 mg"]',                              '["BD"]',                    '[30,60,90]',  'Anticonvulsant'),
('Levipil 500',      'Levetiracetam',             '500 mg',  'Tablet',     '["500 mg"]',                              '["BD"]',                    '[30,60,90]',  'Anticonvulsant'),
('Phenytoin 100',    'Phenytoin Sodium',          '100 mg',  'Tablet',     '["100 mg"]',                              '["TDS","BD"]',              '[30,60,90]',  'Anticonvulsant'),
('Eptoin 100',       'Phenytoin Sodium',          '100 mg',  'Tablet',     '["100 mg"]',                              '["TDS","BD"]',              '[30,60,90]',  'Anticonvulsant'),
('Clonotril 0.5',    'Clonazepam',                '0.5 mg',  'Tablet',     '["0.5 mg"]',                              '["BD"]',                    '[14,30]',     'Benzodiazepine'),
('Diazepam 5',       'Diazepam',                  '5 mg',    'Tablet',     '["5 mg"]',                                '["BD","HS"]',               '[7,14]',      'Benzodiazepine'),
('Stilnoct 10',      'Zolpidem',                  '10 mg',   'Tablet',     '["10 mg"]',                               '["HS"]',                    '[7,14]',      'Hypnotic'),
('Nitrest 10',       'Zolpidem',                  '10 mg',   'Tablet',     '["10 mg"]',                               '["HS"]',                    '[7,14]',      'Hypnotic'),
('Modalert 200',     'Modafinil',                 '200 mg',  'Tablet',     '["200 mg"]',                              '["OD"]',                    '[30,60]',     'Wakefulness Agent'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- DERMATOLOGY
-- ═══════════════════════════════════════════════════════════════════════════════
('Metrogyl 400',     'Metronidazole',             '400 mg',  'Tablet',     '["400 mg"]',                              '["BD"]',                    '[7,14]',      'Antibiotic (ROS)'),
('Acne-UV Gel',      'Adapalene + Benzoyl Peroxide','0.1%/2.5%','Gel',    '["Apply"]',                               '["HS"]',                    '[12,24]','Retinoid / Anti-acne'),
('Acretin 0.1%',     'Adapalene',                 '0.1%',    'Cream',      '["Apply"]',                               '["HS"]',                    '[8,12]','Retinoid'),
('Tretin 0.05%',     'Tretinoin',                 '0.05%',   'Cream',      '["Apply"]',                               '["HS"]',                    '[8,12]','Retinoid'),
('Kojivit Gel',      'Kojic Acid + Arbutin + Vitamin C', 'Gel', 'Gel',   '["Apply"]',                               '["BD"]',                    '[8,12]','Depigmenting'),
('Hydroquinone Cream','Hydroquinone',             '2%',      'Cream',      '["Apply"]',                               '["BD"]',                    '[8,12]','Depigmenting'),
('Suncros 50',       'Zinc Oxide + Tinosorb S',   '50 SPF',  'Sunscreen',  '["Apply"]',                               '["Morning","Reapply"]',     '[30,60]','Sunscreen'),
('Photostable Gold', 'Ethylhexyl Methoxycinnamate','50 SPF', 'Sunscreen',  '["Apply"]',                               '["Morning","Reapply"]',     '[30,60]','Sunscreen'),
('Ureaderm 10',      'Urea',                      '10%',     'Cream',      '["Apply"]',                               '["BD"]',                    '[14,30]',     'Moisturizer'),
('Cetaphil DAM',     'Emollient',                 'Apply',   'Cream',      '["Apply"]',                               '["BD"]',                    '[30,60]',     'Emollient'),
('Episoft Lotion',   'Lotion',                    'Apply',   'Lotion',     '["Apply"]',                               '["BD"]',                    '[30,60]',     'Emollient'),
('Tacroz 0.1%',      'Tacrolimus',                '0.1%',    'Ointment',   '["Apply"]',                               '["BD"]',                    '[14,30]',     'Immunomodulator'),
('Permethrin 5%',    'Permethrin',                '5%',      'Cream',      '["Apply overnight"]',                     '["Once, repeat 1 wk"]',     '[1]',         'Pediculosicide'),
('Betnovate',        'Betamethasone Valerate',    '0.1%',    'Cream',      '["Apply"]',                               '["BD"]',                    '[7,14]',      'Corticosteroid (Topical)'),
('Betnovate-C',      'Betamethasone + Clotrimazole','0.1%/1%','Cream',    '["Apply"]',                               '["BD"]',                    '[7,14]',      'Corticosteroid + Antifungal'),
('Tenovate',         'Clobetasol',                '0.05%',   'Cream',      '["Apply"]',                               '["BD"]',                    '[7,14]',      'Corticosteroid (Topical)'),
('Diprovate G',      'Betamethasone Dipropionate + Gentamicin','Cream', 'Cream', '["Apply"]',             '["BD"]',                    '[7,14]',      'Corticosteroid + Antibiotic'),
('Fucibet',          'Fusidic Acid + Betamethasone','2%/0.1%','Cream',     '["Apply"]',                               '["BD"]',                    '[7,14]',      'Antibiotic + Corticosteroid'),
('Fucidin H',        'Fusidic Acid + Hydrocortisone','2%/1%','Cream',      '["Apply"]',                               '["BD"]',                    '[7,14]',      'Antibiotic + Corticosteroid'),
('Fucidin',          'Fusidic Acid',              '2%',      'Cream',      '["Apply"]',                               '["BD"]',                    '[7,14]',      'Antibiotic (Topical)'),
('Candid-B',         'Clotrimazole + Beclomethasone','1%/0.025%','Cream',  '["Apply"]',                               '["BD"]',                    '[7,14]',      'Antifungal + Corticosteroid'),
('Dermi 5',          'Fluocinolone Acetonide',    '0.025%',  'Cream',      '["Apply"]',                               '["BD"]',                    '[7,14]',      'Corticosteroid (Topical)'),
('Nixocream',        'Permethrin',                '5%',      'Cream',      '["Apply"]',                               '["Once, repeat 1 wk"]',     '[1]',         'Scabies'),
('Ivermectin 12',    'Ivermectin',                '12 mg',   'Tablet',     '["12 mg"]',                               '["OD x2"]',                 '[2]',         'Antiparasitic'),
('Luliconazole 1%',  'Luliconazole',              '1%',      'Cream',      '["Apply"]',                               '["OD"]',                    '[14,28]',     'Antifungal'),
('Sertaconazole 2%', 'Sertaconazole',             '2%',      'Cream',      '["Apply"]',                               '["BD"]',                    '[14,28]',     'Antifungal'),
('Terbinafine 250',  'Terbinafine',               '250 mg',  'Tablet',     '["250 mg"]',                              '["OD"]',                    '[6,12]','Antifungal'),
('Tinaderm',         'Terbinafine',               '1%',      'Cream',      '["Apply"]',                               '["BD"]',                    '[14,28]',     'Antifungal'),
('Canesten Cream',   'Clotrimazole',              '1%',      'Cream',      '["Apply"]',                               '["BD"]',                    '[14,28]',     'Antifungal'),
('Miconazole 2%',    'Miconazole',                '2%',      'Cream',      '["Apply"]',                               '["BD"]',                    '[14,28]',     'Antifungal'),
('Ketodash',         'Ketoconazole',              '2%',      'Shampoo',    '["Apply"]',                               '["2x/week"]',               '[4]',   'Antifungal Shampoo'),
('Nizoral',          'Ketoconazole',              '2%',      'Shampoo',    '["Apply"]',                               '["2x/week"]',               '[4]',   'Antifungal Shampoo'),
('Scabicid',         'Permethrin',                '5%',      'Cream',      '["Apply"]',                               '["Once, repeat 1 wk"]',     '[1]',         'Scabies'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- OPHTHALMIC
-- ═══════════════════════════════════════════════════════════════════════════════
('Moxifresh 0.5%',   'Moxifloxacin',              '0.5%',    'Eye Drops',  '["1 drop"]',                              '["TDS","QID"]',             '[7,14]',      'Antibiotic (Ophthalmic)'),
('Moxicip 0.5%',     'Moxifloxacin',              '0.5%',    'Eye Drops',  '["1 drop"]',                              '["QID"]',                   '[7,14]',      'Antibiotic (Ophthalmic)'),
('Tobracid',         'Tobramycin',                '0.3%',    'Eye Drops',  '["1-2 drops"]',                           '["QID"]',                   '[7,14]',      'Antibiotic (Ophthalmic)'),
('Cromal 2%',        'Cromoglycate',              '2%',      'Eye Drops',  '["1-2 drops"]',                           '["QID"]',                   '[14,30]',     'Anti-allergic (Ophthalmic)'),
('Olofast',          'Olopatadine',               '0.1%',    'Eye Drops',  '["1 drop"]',                              '["BD"]',                    '[14,30]',     'Anti-allergic (Ophthalmic)'),
('Pataday',          'Olopatadine',               '0.1%',    'Eye Drops',  '["1 drop"]',                              '["OD"]',                    '[14,30]',     'Anti-allergic (Ophthalmic)'),
('FML',              'Fluorometholone',           '0.1%',    'Eye Drops',  '["1-2 drops"]',                           '["QID"]',                   '[7,14]',      'Corticosteroid (Ophthalmic)'),
('Pred Forte',       'Prednisolone Acetate',      '1%',      'Eye Drops',  '["1-2 drops"]',                           '["QID"]',                   '[7,14]',      'Corticosteroid (Ophthalmic)'),
('Timoptol 0.5%',    'Timolol',                   '0.5%',    'Eye Drops',  '["1 drop"]',                              '["BD"]',                    '[30,60,90]',  'Anti-glaucoma'),
('Timoptol 0.25%',   'Timolol',                   '0.25%',   'Eye Drops',  '["1 drop"]',                              '["BD"]',                    '[30,60,90]',  'Anti-glaucoma'),
('Xalatan',          'Latanoprost',               '0.005%',  'Eye Drops',  '["1 drop"]',                              '["HS"]',                    '[30,60,90]',  'Anti-glaucoma'),
('Tropicamide 1%',   'Tropicamide',               '1%',      'Eye Drops',  '["1-2 drops"]',                           '["Pre-procedure"]',         '[0]',         'Mydriatic'),
('Cyclopentolate 1%', 'Cyclopentolate',           '1%',      'Eye Drops',  '["1 drop"]',                              '["Pre-procedure"]',         '[0]',         'Mydriatic'),
('Poly Tears',       'Hydroxypropyl Methylcellulose','0.3%',  'Eye Drops',  '["1-2 drops"]',                           '["PRN"]',                   '[30,60]',     'Lubricant'),
('Refresh Tears',    'Carboxymethylcellulose',    '0.5%',    'Eye Drops',  '["1-2 drops"]',                           '["PRN"]',                   '[30,60]',     'Lubricant'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- ENT
-- ═══════════════════════════════════════════════════════════════════════════════
('Otrivin 0.05%',    'Xylometazoline',            '0.05%',   'Nasal Drops','["2 drops each naris"]',                 '["BD"]',                    '[3,5]',       'Nasal Decongestant'),
('Otrivin 0.1%',     'Xylometazoline',            '0.1%',    'Nasal Drops','["2-3 drops each naris"]',               '["BD"]',                    '[3,5]',       'Nasal Decongestant'),
('Otrivin Nasal',    'Xylometazoline',            '0.1%',    'Nasal Spray','["1-2 sprays each naris"]',              '["BD"]',                    '[3,5]',       'Nasal Decongestant'),
('Olofresh',         'Olopatadine + Mometasone',  'Nasal Spray','Nasal Spray','["2 sprays each naris"]',            '["OD"]',                    '[14,30]',     'Nasal Anti-allergic'),
('Nasomet',          'Mometasone Furoate',        '50 mcg',  'Nasal Spray','["2 sprays each naris"]',               '["OD"]',                    '[14,30]',     'Nasal Corticosteroid'),
('Rhinocort',        'Budesonide',                '64 mcg',  'Nasal Spray','["2 sprays each naris"]',               '["OD"]',                    '[14,30]',     'Nasal Corticosteroid'),
('Nasalide',         'Fluticasone Propionate',    '50 mcg',  'Nasal Spray','["2 sprays each naris"]',               '["OD"]',                    '[14,30]',     'Nasal Corticosteroid'),
('Ciplox Ear',       'Ciprofloxacin',             '0.3%',    'Ear Drops',  '["2-3 drops"]',                          '["BD"]',                    '[7,14]',      'Antibiotic (Otic)'),
('Oflo Ear',         'Ofloxacin',                 '0.3%',    'Ear Drops',  '["2-3 drops"]',                          '["BD"]',                    '[7,14]',      'Antibiotic (Otic)'),
('Soliwax',          'Sodium Bicarbonate + Urea',  'Ear Drops','Ear Drops',  '["2-3 drops"]',                         '["BD"]',                    '[3,5]',       'Cerumenolytic'),
('Waxol',            'Cerumenolytic',             'Drops',   'Ear Drops',  '["2-3 drops"]',                          '["BD"]',                    '[3,5]',       'Cerumenolytic'),
('Tinnex',           'Paracetamol + Phenylephrine + Chlorpheniramine', 'Syrup', 'Syrup', '["10 ml"]', '["TDS"]', '[3,5]',    'Cold / Cough'),
('Ascoril Cough Syrup','Terbutaline + Bromhexine + Guaifenesin','Syrup', 'Syrup', '["10 ml"]', '["TDS"]', '[7,14]',  'Cough Syrup'),
('Cheston Cold',     'Phenylephrine + Chlorpheniramine + Paracetamol','Tablet', 'Tablet', '["1 tab"]', '["TDS"]', '[3,5]', 'Cold'),
('Okacet Active',    'Cetirizine + Paracetamol + Pseudoephedrine','Tablet', 'Tablet', '["1 tab"]', '["TDS"]', '[3,5]', 'Cold'),
('Tess 2.5',         'Terbutaline',              '2.5 mg',  'Tablet',     '["2.5 mg"]',                              '["TDS"]',                   '[7,14]',      'Bronchodilator'),
('Cofcold Gold',     'Paracetamol + Caffeine + Phenylephrine + Chlorpheniramine','Tablet', 'Tablet', '["1 tab"]', '["TDS"]', '[3,5]', 'Cold'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- MUSCULOSKELETAL / ORTHO
-- ═══════════════════════════════════════════════════════════════════════════════
('Calciquick D3',    'Cholecalciferol',           '60000 IU','Tablet',     '["60000 IU"]',                           '["Weekly x4-8"]',          '[4,8]', 'Vitamin D'),
('Hyaluronic Acid',  'Hyaluronic Acid',           'Intra-articular','Injection','["20 mg"]',                       '["As directed"]',           '[0]',         'Viscosupplement'),
('Thiocolchicoside 4','Thiocolchicoside',         '4 mg',    'Tablet',     '["4 mg"]',                                '["BD","TDS"]',              '[3,5]',       'Muscle Relaxant'),
('Tolperisone 150',  'Tolperisone',               '150 mg',  'Tablet',     '["150 mg"]',                              '["TDS"]',                   '[7,14]',      'Muscle Relaxant'),
('Myospaz 4',        'Thiocolchicoside',          '4 mg',    'Tablet',     '["4 mg"]',                                '["BD"]',                    '[3,5]',       'Muscle Relaxant'),
('Chlorzoxazone 500','Chlorzoxazone',             '500 mg',  'Tablet',     '["500 mg"]',                              '["TDS"]',                   '[3,5]',       'Muscle Relaxant'),
('Cyclopam',         'Dicyclomine',               '20 mg',   'Tablet',     '["20 mg"]',                               '["TDS","QID"]',             '[3,5]',       'Antispasmodic'),
('Dicyclomine 10',   'Dicyclomine',               '10 mg',   'Tablet',     '["10 mg"]',                               '["TDS"]',                   '[3,5]',       'Antispasmodic'),
('Buscopan',         'Hyoscine Butylbromide',     '10 mg',   'Tablet',     '["10 mg"]',                               '["TDS","SOS"]',             '[3,5]',       'Antispasmodic'),
('Spasmonil',        'Phaverine',                 '40 mg',   'Tablet',     '["40 mg"]',                               '["TDS"]',                   '[3,5]',       'Antispasmodic'),
('Colospa Retard',   'Mebeverine',                '200 mg',  'Tablet (SR)','["200 mg"]',                              '["BD"]',                    '[7,14]',      'Antispasmodic'),
('Dycimin',          'Dicyclomine',               '20 mg',   'Injection',  '["20 mg"]',                               '["IM"]',                    '[3,5]',       'Antispasmodic'),
('Flexon MR',        'Thiocolchicoside + Diclofenac + Paracetamol','SR Tablet','Tablet', '["1 tab"]',          '["BD"]',                    '[3,5]',       'Combination Analgesic'),
('Myorub Plus',      'Chlorzoxazone + Diclofenac + Paracetamol','Tablet','Tablet', '["1 tab"]',                         '["BD"]',                    '[3,5]',       'Combination Analgesic'),
('Cipzer Guggulu',   'Guggulu + Triphala',        '1 tab',   'Tablet',     '["1 tab"]',                               '["BD"]',                    '[30,60]',     'Ayurvedic Anti-inflammatory'),
('Ace proxyvon',     'Aceclofenac + Paracetamol + Chlorzoxazone','Tablet', 'Tablet', '["1 tab"]',                     '["BD"]',                    '[3,5]',       'Combination Analgesic'),
('Ostocalcium B12',  'Calcium + Vitamin D3 + B12','Tablet',  'Tablet',     '["1 tab"]',                               '["OD","BD"]',               '[30,60]',     'Calcium + Vit D + B12'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- UROLOGICAL
-- ═══════════════════════════════════════════════════════════════════════════════
('Tamsulosin 0.4',   'Tamsulosin',                '0.4 mg',  'Capsule (SR)','["0.4 mg"]',                             '["OD"]',                    '[30,60,90]',  'Alpha-blocker'),
('Flomax 0.4',       'Tamsulosin',                '0.4 mg',  'Capsule',    '["0.4 mg"]',                              '["OD"]',                    '[30,60,90]',  'Alpha-blocker'),
('Silodal 8',        'Silodosin',                 '8 mg',    'Capsule',    '["8 mg"]',                                '["OD"]',                    '[30,60,90]',  'Alpha-blocker'),
('Tablo CV',         'Tadalafil',                 '5 mg',    'Tablet',     '["5 mg"]',                                '["OD"]',                    '[30,60,90]',  'PDE5 Inhibitor'),
('Sildenafil 50',    'Sildenafil',                '50 mg',   'Tablet',     '["50 mg"]',                               '["PRN"]',                   '[0]',         'PDE5 Inhibitor'),
('Suhagra 50',       'Sildenafil',                '50 mg',   'Tablet',     '["50 mg"]',                               '["PRN"]',                   '[0]',         'PDE5 Inhibitor'),
('Tadalafil 10',     'Tadalafil',                 '10 mg',   'Tablet',     '["10 mg"]',                               '["PRN"]',                   '[0]',         'PDE5 Inhibitor'),
('Urispas 200',      'Flavoxate',                 '200 mg',  'Tablet',     '["200 mg"]',                              '["TDS"]',                   '[7,14]',      'Urinary Antispasmodic'),
('Tolterodine 2',    'Tolterodine',               '2 mg',    'Tablet',     '["2 mg"]',                                '["BD"]',                    '[30,60]',     'Anticholinergic'),
('Detrusitol 2',     'Tolterodine',               '2 mg',    'Tablet',     '["2 mg"]',                                '["BD"]',                    '[30,60]',     'Anticholinergic'),
('Uroflow 5',        'Tamsulosin + Dutasteride',  '0.4/0.5 mg','Capsule', '["0.4/0.5 mg"]',                          '["OD"]',                    '[30,60,90]',  'Alpha-blocker + 5-alpha Reductase Inhibitor'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- GI / HEPATOPROTECTIVE
-- ═══════════════════════════════════════════════════════════════════════════════
('Ursodiol 300',     'Ursodeoxycholic Acid',      '300 mg',  'Capsule',    '["300 mg"]',                              '["BD"]',                    '[30,60,90]',  'Hepatoprotective'),
('Liv 52',           'Caper Bush + Chicory',      '2 tab',   'Tablet',     '["2 tabs"]',                              '["BD"]',                    '[30,60]',     'Hepatoprotective'),
('Hepamerz',         'L-Ornithine L-Aspartate',   '3 g',     'Powder',     '["3 g"]',                                 '["BD","TDS"]',              '[14,30]',     'Hepatoprotective'),
('Neem',             'Azadirachta indica',        '500 mg',  'Tablet',     '["500 mg"]',                              '["BD"]',                    '[30,60]',     'Hepatoprotective'),
('Livofit Z',        'Probiotic + Prebiotic',     '1 sachet','Powder',     '["1 sachet"]',                            '["OD"]',                    '[14,30]',     'Probiotic'),
('Ecologic 62.5',    'Probiotic Blend',           '1 cap',   'Capsule',    '["1 cap"]',                               '["OD"]',                    '[14,30]',     'Probiotic'),
('Dramamine',        'Dimenhydrinate',            '50 mg',   'Tablet',     '["50 mg"]',                               '["TDS"]',                   '[3,5]',       'Antiemetic (Motion Sickness)'),
('Vertin 16',        'Betahistine',               '16 mg',   'Tablet',     '["16 mg"]',                               '["BD"]',                    '[14,30]',     'Vertigo'),
('Betahistine 16',   'Betahistine',               '16 mg',   'Tablet',     '["16 mg"]',                               '["BD"]',                    '[14,30]',     'Vertigo'),
('Betahistine 8',    'Betahistine',               '8 mg',    'Tablet',     '["8 mg"]',                                '["BD"]',                    '[14,30]',     'Vertigo'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- CONTRACEPTION / GYNECOLOGY
-- ═══════════════════════════════════════════════════════════════════════════════
('Ovral L',          'Levonorgestrel + Ethinyl Estradiol','0.15/0.03 mg', 'Tablet', '["1 tab daily"]', '["21 days + 7 off"]', '[30]', 'Oral Contraceptive'),
('Femilon',          'Desogestrel + Ethinyl Estradiol','0.15/0.03 mg', 'Tablet', '["1 tab daily"]', '["21 days + 7 off"]', '[30]', 'Oral Contraceptive'),
('Loette',           'Levonorgestrel + Ethinyl Estradiol','0.1/0.02 mg', 'Tablet', '["1 tab daily"]', '["21 days + 7 off"]', '[30]', 'Oral Contraceptive'),
('i-Pill',           'Levonorgestrel',            '1.5 mg',  'Tablet',     '["1.5 mg"]',                              '["Single dose"]',           '[0]',         'Emergency Contraceptive'),
('Postinor-2',       'Levonorgestrel',            '0.75 mg', 'Tablet',     '["0.75 mg x2"]',                          '["12h apart"]',             '[0]',         'Emergency Contraceptive'),
('Deviry',           'Medroxyprogesterone',       '10 mg',   'Tablet',     '["10 mg"]',                               '["OD"]',                    '[5,10]', 'Progestogen'),
('Menostar',         'Norethisterone',            '5 mg',    'Tablet',     '["5 mg"]',                                '["TDS"]',                   '[5,10]', 'Progestogen'),
('Megace ES',        'Megestrol Acetate',         '40 mg/ml','Oral Suspension','["5 ml"]',                          '["BD"]',                    '[30,60]',     'Appetite Stimulant'),
('Fergrad C',        'Iron + Vitamin C',          '100 mg',  'Tablet (SR)','["100 mg"]',                              '["OD"]',                    '[30,60,90]',  'Iron Supplement'),
('GnRH Agonist',     'Leuprolide',                '3.75 mg', 'Injection',  '["3.75 mg"]',                             '["Monthly"]',               '[30,180]','Hormone Therapy'),
('Clomid 50',        'Clomiphene Citrate',        '50 mg',   'Tablet',     '["50 mg"]',                               '["OD x5 days"]',            '[28]',   'Ovulation Induction'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- MISCELLANEOUS / EMERGENCY
-- ═══════════════════════════════════════════════════════════════════════════════
('Adrenaline 1 mg',  'Epinephrine',              '1 mg/1ml','Injection',  '["0.5-1 mg IM"]',                         '["SOS"]',                   '[0]',         'Emergency'),
('Atropine 0.6 mg',  'Atropine Sulphate',         '0.6 mg/1ml','Injection','["0.6 mg"]',                              '["SOS"]',                   '[0]',         'Emergency'),
('Diazepam 5 mg',    'Diazepam',                  '5 mg/2ml','Injection',  '["5 mg"]',                                '["IV slow"]',               '[0]',         'Emergency'),
('Phenytoin 150 mg', 'Phenytoin Sodium',          '150 mg/2ml','Injection','["150 mg"]',                              '["IV slow"]',               '[0]',         'Emergency'),
('Noradrenaline',    'Norepinephrine',            '4 mg/4ml','Injection',  '["As directed"]',                         '["IV infusion"]',           '[0]',         'Vasopressor'),
('Dobutamine',       'Dobutamine',                '250 mg',  'Injection',  '["250 mg"]',                              '["IV infusion"]',           '[0]',         'Inotrope'),
('Ranitidine 50 mg', 'Ranitidine',                '50 mg/2ml','Injection', '["50 mg"]',                               '["IV"]',                    '[0]',         'GI (Emergency)'),
('Ondansetron 4 mg', 'Ondansetron',               '4 mg/2ml','Injection',  '["4 mg"]',                                '["IV"]',                    '[0]',         'Antiemetic (IV)'),
('Paracetamol 1 g',  'Paracetamol',               '1 g/100ml','IV Infusion','["1 g"]',                               '["TDS"]',                   '[3,5]',       'IV Analgesic / Antipyretic'),
('Tramadol 100 mg',  'Tramadol',                  '100 mg/2ml','Injection','["100 mg"]',                              '["IM","IV slow"]',          '[3,5]',       'Opioid Analgesic'),
('Diclofenac 75 mg', 'Diclofenac',                '75 mg/3ml','Injection', '["75 mg"]',                               '["IM"]',                    '[3,5]',       'NSAID (IM)'),
('Diclofenac 25 mg', 'Diclofenac',                '25 mg/3ml','Suppository','["25 mg"]',                              '["PR"]',                    '[3,5]',       'NSAID (PR)'),
('Betamethasone 4 mg','Betamethasone',            '4 mg/1ml','Injection',  '["4 mg"]',                                '["IM"]',                    '[0]',         'Corticosteroid'),
('Dexamethasone 4 mg','Dexamethasone',            '4 mg/1ml','Injection',  '["4 mg"]',                                '["IM","IV"]',               '[0]',         'Corticosteroid'),
('Hydrocortisone 100','Hydrocortisone',           '100 mg',  'Injection',  '["100 mg"]',                              '["IV"]',                    '[0]',         'Corticosteroid'),
('Dexa 4',           'Dexamethasone',             '4 mg',    'Tablet',     '["4 mg"]',                                '["OD"]',                    '[5,14]',      'Corticosteroid'),
('Decadron 4',       'Dexamethasone',             '4 mg',    'Tablet',     '["4 mg"]',                                '["OD"]',                    '[5,14]',      'Corticosteroid'),
('Pan 40 IV',        'Pantoprazole',              '40 mg',   'Injection',  '["40 mg"]',                               '["IV"]',                    '[3,5]',       'PPI (IV)'),
('Zinetac 150',      'Ranitidine',                '150 mg',  'Tablet',     '["150 mg"]',                              '["BD"]',                    '[14,28]',     'H2 Blocker'),
('Tetanus Toxoid',   'Tetanus Toxoid',            '0.5 ml',  'Injection',  '["0.5 ml"]',                              '["Single"]',                '[0]',         'Vaccine'),
('TT Booster',       'Tetanus Toxoid',            '0.5 ml',  'Injection',  '["0.5 ml"]',                              '["Booster"]',               '[0]',         'Vaccine');
